#ifndef USER_SERVICE_H
#define USER_SERVICE_H

#include <grpcpp/grpcpp.h>
#include "user_management.pb.h" // Generated by gRPC
#include "user_management.grpc.pb.h" // Generated by gRPC
using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;


namespace user_management {
class UserServiceImpl final : public UserService::Service {
public:
    grpc::Status RegisterUser(ServerContext* context, const RegisterUserRequest* request,RegisterUserResponse* response) override ;
    grpc::Status LoginUser(ServerContext* context, const LoginUserRequest* request,LoginUserResponse* response) override ;
    grpc::Status GetUserProfile(ServerContext* context, const GetUserProfileRequest* request,GetUserProfileResponse* response) override ;
    // Add other methods as needed
};
}

#endif // USER_SERVICE_H

